# Generated by Django 4.2.1 on 2023-12-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopoe', '0002_article_country_article_creator_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default='0', max_length=64, primary_key=True, serialize=False),
        ),
    ]
