# Generated by Django 4.2.1 on 2023-12-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopoe', '0004_alter_article_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
