# Generated by Django 4.2.1 on 2023-12-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoopoe', '0006_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubDate',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
