# Generated by Django 4.2.1 on 2023-12-26 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoopoe', '0009_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'verbose_name_plural': 'Savings'},
        ),
        migrations.AlterField(
            model_name='saved',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoopoe.article'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
